#!/bin/bash
MAJOR_MINOR_VERSION=2.0     # Major.Minor
STARTING_BUILD_NUMBER=0     # Discount the offset for patch version number

echo $MAJOR_MINOR_VERSION
echo $BITBUCKET_BUILD_NUMBER
echo $STARTING_BUILD_NUMBER

PATCH_VERSION=$(($BITBUCKET_BUILD_NUMBER - $STARTING_BUILD_NUMBER))

echo $PATCH_VERSION

export SEMANTIC_VERSION="${MAJOR_MINOR_VERSION}.${PATCH_VERSION}"

echo $SEMANTIC_VERSION

LATEST_VERSION_NAME=$BITBUCKET_BRANCH
echo $LATEST_VERSION_NAME

if [ "$LATEST_VERSION_NAME" = "main" ]; then
    LATEST_VERSION_NAME="latest"
fi

echo $LATEST_VERSION_NAME

